services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salesflow-crm
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: "sqlserver://172.28.10.2\\MFILES_SQL;database=SalesFlowCRM;user=salesflow_app;password=*G3x-adZCh_KZ2im;encrypt=true;trustServerCertificate=true"
      NEXTAUTH_SECRET: "change-this-to-a-real-secret-min-32-chars!!"
      NEXTAUTH_URL: "http://192.168.1.197:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
